<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_master_data</name>
   <tag></tag>
   <elementGuidId>4fa9a089-1896-4be2-84a6-bfdc173267e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mQuotation-25</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mQuotation-25']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68fd9089-d494-4625-b8b4-c618c72bdddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>36c546d9-659f-491a-a888-2570f984e73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mQuotation-25</value>
      <webElementGuid>d705ac75-2c95-4685-b14c-79c294ac93d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox w-6 h-6 rounded-md mr-4 form-check appearance-none checked:border-0 checked:bg-secondary border-2 border-placeholder</value>
      <webElementGuid>3bff7f30-ebd3-4fc4-956d-3e877d768452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accessbility</value>
      <webElementGuid>ed7dde3f-2d44-40c0-b135-8d69316976b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>34</value>
      <webElementGuid>5e9e614a-879d-4adf-9995-41d07482e1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mQuotation-25&quot;)</value>
      <webElementGuid>15cec4ba-40ad-475a-8152-7d29440ed0c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mQuotation-25']</value>
      <webElementGuid>006c4b00-0872-4dc6-acec-65da5be912e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-12']/div/div[2]/div/form/div/div[2]/div[9]/div[26]/input</value>
      <webElementGuid>e5f701d5-8fda-4066-bd78-89de8921891f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/input</value>
      <webElementGuid>df990b40-57f3-4a0f-bf3f-edbe708a2d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mQuotation-25' and @name = 'accessbility']</value>
      <webElementGuid>5a72ff2c-e558-4bc7-ba5f-1d793fd23437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
