<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_trucking_instruction</name>
   <tag></tag>
   <elementGuidId>c6250228-b9e4-4218-b16f-fa8cc0692635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mQuotation-61</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mQuotation-61']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73309c7d-4601-4934-b45c-8b2e3e4dffb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>93eee024-cebb-4dc1-9431-046b179ad060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mQuotation-61</value>
      <webElementGuid>13b2c526-8619-4742-af5f-a222ea8044b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox w-6 h-6 rounded-md mr-4 form-check appearance-none checked:border-0 checked:bg-secondary border-2 border-placeholder</value>
      <webElementGuid>04481c16-0a59-41d3-b7ac-19e4bb5b90eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accessbility</value>
      <webElementGuid>07f18fed-5220-4ea6-b3cb-974620bacefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>84</value>
      <webElementGuid>95242bc5-fd92-4747-9d56-dd86407663c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mQuotation-61&quot;)</value>
      <webElementGuid>683006d0-5946-4486-970d-d793fc3ac845</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mQuotation-61']</value>
      <webElementGuid>138f4060-bda5-4dce-839f-960917ec9b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-12']/div/div[2]/div/form/div/div[2]/div[9]/div[62]/input</value>
      <webElementGuid>e04b85d3-b43d-4989-92ae-7a206d618a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[62]/input</value>
      <webElementGuid>0ebc9ba3-38bc-41d2-b4dc-543bd4c9d2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mQuotation-61' and @name = 'accessbility']</value>
      <webElementGuid>d853d03e-49fd-4438-8237-2c5b8232772f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
