<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_quotation_spv</name>
   <tag></tag>
   <elementGuidId>5f4ae0d0-611d-4251-833e-4e46aae3c685</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mQuotation-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mQuotation-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa23c55b-8973-404b-8f4e-b0d60aed1e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3ec1d525-2925-4ef0-b825-8f87ddb8a747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mQuotation-2</value>
      <webElementGuid>df9a6039-c063-4cc7-9520-7ba97109a30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox w-6 h-6 rounded-md mr-4 form-check appearance-none checked:border-0 checked:bg-secondary border-2 border-placeholder</value>
      <webElementGuid>414200dc-a2f4-4e3e-9f4f-98e12be9576c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accessbility</value>
      <webElementGuid>86426195-64b7-4685-8300-c0f63588e813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9a551611-0bb6-44f2-8dcc-3387671a96ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mQuotation-2&quot;)</value>
      <webElementGuid>73ea7e48-002d-4562-8bc2-fd563fd22260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mQuotation-2']</value>
      <webElementGuid>9278b620-72d8-46b0-af82-83bd5f19b22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-12']/div/div[2]/div/form/div/div[2]/div[9]/div[3]/input</value>
      <webElementGuid>1656204f-7f97-429c-9621-ca86aa18df3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>7cd937cf-3755-4b70-b0ec-501331a52d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mQuotation-2' and @name = 'accessbility']</value>
      <webElementGuid>af073d0a-7213-4ac8-ba41-438eb8df0936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
