<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_quotation</name>
   <tag></tag>
   <elementGuidId>c02bb87f-30fc-4229-8146-a9dd56991dc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mQuotation-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mQuotation-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd5edf1e-3b42-4fa6-9e0f-9c680963ce3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c01204c1-76a2-4e5b-bdac-34dc08f1c08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mQuotation-1</value>
      <webElementGuid>fa29175b-772f-48ae-a9ab-de30f273524a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox w-6 h-6 rounded-md mr-4 form-check appearance-none checked:border-0 checked:bg-secondary border-2 border-placeholder</value>
      <webElementGuid>85f5ab17-0cb9-4718-9756-f1bb27dd4e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accessbility</value>
      <webElementGuid>6ae51932-fbab-47e6-9cd2-7a8174a0bc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2ae2201b-c5b6-4835-9b61-2fc79d1b4a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mQuotation-1&quot;)</value>
      <webElementGuid>298bf684-87ba-4e8d-8a93-c64a82a8198d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mQuotation-1']</value>
      <webElementGuid>e2a339e0-a71f-4d27-bd90-621a89b6458e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-12']/div/div[2]/div/form/div/div[2]/div[9]/div[2]/input</value>
      <webElementGuid>89c55cc4-8c45-4299-8e18-e1190c2fbbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b58f84a8-4a3d-4471-b42c-1e5ed407762b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mQuotation-1' and @name = 'accessbility']</value>
      <webElementGuid>3e134c08-72f1-4137-978f-271527209dce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
