<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse_avatar</name>
   <tag></tag>
   <elementGuidId>512d8dbc-275c-4c58-a521-461533c2ed2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='avatar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;avatar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ecb43d3-04e0-4bb8-bb52-ff505181383a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>926b8baf-8a6e-4703-bb53-2c08a21d0a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>ee4743ea-72a4-4297-b632-e966afde6223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full absolute h-[80%] opacity-0 cursor-pointer top-0</value>
      <webElementGuid>1363cdf0-6d50-4630-ae91-cdb3fea45849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>9a503b2b-4bbd-48fe-adbc-8450c5a45089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-12&quot;)/div[@class=&quot;flex min-h-screen items-center justify-center px-4 pt-4 text-center sm:block sm:items-end sm:p-0 lg:pb-20&quot;]/div[@class=&quot;relative inline-block w-[95%] flex-grow transform overflow-hidden text-left align-bottom transition-all sm:my-8 sm:w-[auto] sm:align-middle&quot;]/div[@class=&quot;w-full sm:w-[579px] p-8 bg-white rounded-xl&quot;]/form[1]/section[1]/div[@class=&quot;bg-bg rounded-xl min-h-[190px] flex flex-col justify-center items-center text-label relative border-[1px] border-dashed border-placeholder&quot;]/input[@class=&quot;w-full absolute h-[80%] opacity-0 cursor-pointer top-0&quot;]</value>
      <webElementGuid>cb7671ec-adf1-4ff4-9e8f-42114e6e2fc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='avatar']</value>
      <webElementGuid>bb59330d-0b60-4981-b3f5-4c8f71f6e1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-12']/div/div[2]/div/form/section/div/input[2]</value>
      <webElementGuid>8d0b06f2-bd90-47f7-b356-2dd2a70ffbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>e92a2d53-5c06-40a9-9b12-b56f012fa9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'avatar' and @type = 'file']</value>
      <webElementGuid>88bd5595-3d10-4c40-b6de-334a925f94e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
