<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>auth</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5890ec36-05b1-4a57-a8ba-0d01aea4786e</testSuiteGuid>
   <testCaseLink>
      <guid>c196c9e2-3e2c-49e2-a413-1ac92265762d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/auth/auth_TC_1_Check_Mandatory_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee7f4919-8cd3-4056-bb04-6f7d4e020683</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0973d4fd-caa1-4aff-8fed-d540d6997633</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/auth/auth_TC_2_wrong_email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2fbae7e-23c7-4744-b8aa-993828507be2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30fa4d32-4fbd-42cb-9404-b4c64bec68d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/auth/auth_TC_3_wrong_password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3be56c94-41b6-4aad-86c3-f97667704dc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>02aa374c-f177-41f1-8aad-35618c6f52d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/auth/auth_TC_4_view_password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ce9eaa4-116d-4038-b3db-6906977eba26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f69beadf-cd7b-4c46-8091-33a5dfaad9a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/auth/auth_TC_5_login_sucess</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1ba43d5-65df-4562-923b-0d58040aca43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94ecc992-575b-4fa1-b9be-1ccf6c599ea7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90747cc0-0b9a-4f84-be53-444b9739cee1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
