<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>office_tambah_dropdown_kota_value</name>
   <tag></tag>
   <elementGuidId>1cab9197-755a-4b1b-8a0c-06854ddcaa3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-combobox-button-10']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-button-10 > div.absolute.inset-y-0.right-0.flex.items-center.pr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76a98021-5f2a-4aa4-a60b-e3f4d644e3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-y-0 right-0 flex items-center pr-2</value>
      <webElementGuid>652bd4fa-4161-42c2-ba78-555a3d55be1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-button-10&quot;)/div[@class=&quot;absolute inset-y-0 right-0 flex items-center pr-2&quot;]</value>
      <webElementGuid>66421eac-26c0-4d03-a877-d13e0774be7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-combobox-button-10']/div</value>
      <webElementGuid>30231f1b-23fe-4f94-8153-f14cfb151556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telepon'])[5]/following::div[8]</value>
      <webElementGuid>99ecc0d7-eee5-4fe8-b742-5bb38fabec1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[9]</value>
      <webElementGuid>ac94b851-209f-4b0a-a887-ab4dbb2ff3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Gedung/Bangunan'])[1]/preceding::div[1]</value>
      <webElementGuid>945ce1aa-279e-4994-8966-bce2ff791c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atur Lokasi'])[1]/preceding::div[2]</value>
      <webElementGuid>fcbf7e57-94b1-4b47-a65b-79bc815b7c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/button/div</value>
      <webElementGuid>22b27c33-0255-4b3d-82ad-dff799509c71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
