<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>office_tambah_dropdown_provinsi_value</name>
   <tag></tag>
   <elementGuidId>57da2f24-7418-433a-af23-075f6c88baa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-combobox-button-8']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.absolute.inset-y-0.right-0.flex.items-center.pr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>813f4c58-016e-433a-9e5a-2aa66c800cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-y-0 right-0 flex items-center pr-2</value>
      <webElementGuid>46a9e6dc-747f-4538-a874-1949915a24a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-button-8&quot;)/div[@class=&quot;absolute inset-y-0 right-0 flex items-center pr-2&quot;]</value>
      <webElementGuid>4aeca9c7-1cb8-4924-a389-4123861bfa26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-combobox-button-8']/div</value>
      <webElementGuid>ee39ab57-e70f-4585-818b-69dc899eae99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telepon'])[5]/following::div[4]</value>
      <webElementGuid>4df79136-77b1-431e-8bf6-5ceb38b7d6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[5]</value>
      <webElementGuid>1071e4e9-1ac1-4c38-88ce-183b64dd2d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Gedung/Bangunan'])[1]/preceding::div[5]</value>
      <webElementGuid>33d17cf5-9b81-4718-9edb-836b8520cc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atur Lokasi'])[1]/preceding::div[6]</value>
      <webElementGuid>453e5c2b-6822-4f93-a661-6c55cc4d8277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>1c1e65a0-a115-4e8d-81d3-eaaf497f6683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
