<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tab_Inactive</name>
   <tag></tag>
   <elementGuidId>b946c306-c1d8-4b77-be4b-e565d9b63ec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section/main/section/div/div[2]/div[2]/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.whitespace-nowrap.rounded-xl.py-2.px-3.font-semibold.capitalize.text-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>860118ac-2d0b-41df-8cbf-a02a54bb7554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>whitespace-nowrap rounded-xl py-2 px-3 font-semibold capitalize text-label</value>
      <webElementGuid>530e82a4-5279-409a-9c5f-33bb3c7f4d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>bbbdbb7e-45b7-45d0-a33d-cf3138df6305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;flex flex-col w-100 h-[100vh] overflow-hidden&quot;]/main[@class=&quot;bg-bg lg:flex  overflow-y-auto lg:overflow-hidden flex-grow relative&quot;]/section[@class=&quot;relative h-full flex flex-col lg:w-4/5&quot;]/div[@class=&quot;flex-grow overflow-y-auto py-5 sm:px-14&quot;]/div[@class=&quot;p-0 sm:p-7 mb-10&quot;]/div[@class=&quot;my-7&quot;]/div[@class=&quot;flex max-w-full gap-3 py-3 overflow-x-auto sm:overflow-x-hidden sm:py-0&quot;]/button[@class=&quot;whitespace-nowrap rounded-xl py-2 px-3 font-semibold capitalize text-label&quot;]</value>
      <webElementGuid>099148fb-5523-44e9-bfc3-98529edc7e5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/main/section/div/div[2]/div[2]/div/button[2]</value>
      <webElementGuid>f7b1c872-0d06-49a3-85c9-5ee7e1ec7ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::button[1]</value>
      <webElementGuid>8e05d7ee-fa22-45de-89dd-18efb1964407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/following::button[2]</value>
      <webElementGuid>280e42a0-a697-4597-9ae2-d70ee548a815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inactive']/parent::*</value>
      <webElementGuid>c6b073f6-7887-4a26-b61b-d1c1fcc54d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>eb441a8e-eccb-43df-a229-53568dc33068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Inactive' or . = 'Inactive')]</value>
      <webElementGuid>fe618359-5f9b-49f9-a715-35a5bfc1e5ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
