<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detail_office_rpl_surabaya</name>
   <tag></tag>
   <elementGuidId>c10a067f-bd2b-4a52-a8c1-140b0776e301</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-option-26</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ec148d9b-1a70-4827-9241-d3a0494aab58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-default select-none relative py-2 pl-10 pr-4 text-gray-900</value>
      <webElementGuid>f4bec73c-dd90-474a-b52a-811d58d5c2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-option-26</value>
      <webElementGuid>d4255a02-d5ad-4253-9c3a-71d9afd644a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e32a9ece-209a-4c14-8dde-e9805ea15350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9a92f010-7948-47f6-8efd-9aa68a354a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[02] RPL SURABAYA</value>
      <webElementGuid>309a0c96-9361-4011-b297-73284ec280e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-option-26&quot;)</value>
      <webElementGuid>03d76ae8-8abc-40f6-983d-f5e9351daa77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='headlessui-combobox-option-26']</value>
      <webElementGuid>7e218ac1-8627-4ab1-81c7-3845d21edb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headlessui-combobox-options-23']/li[3]</value>
      <webElementGuid>f61c3b10-e683-4c9e-9d07-cf001347f8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[03] RPL SUNTER'])[1]/following::li[1]</value>
      <webElementGuid>f3e87475-ae00-4307-b247-e54f214229d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[01] RPL JKT'])[1]/following::li[2]</value>
      <webElementGuid>f180d72c-3ea7-426e-a81d-b3d0f8b2b582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[01] RPL Jakarta'])[1]/preceding::li[1]</value>
      <webElementGuid>d7568792-fb97-42e3-b485-5335a630e1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>efc7bc10-f8f8-47f6-be24-f34bc93f5c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'headlessui-combobox-option-26' and (text() = '[02] RPL SURABAYA' or . = '[02] RPL SURABAYA')]</value>
      <webElementGuid>4641284b-e31b-4176-9e48-b19e3884121a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
