<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detail_role</name>
   <tag></tag>
   <elementGuidId>24839774-737e-45a7-87a1-06c333d28ee9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-19']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-input-19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f83825f-accb-43b9-9bb8-b4775a9fef6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-19</value>
      <webElementGuid>350e8a7d-e86c-4816-bd5e-70291160aeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>02dc9b8a-ae5c-46e9-9109-053ccfd54ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-left border-2 border-line rounded-xl p-4 text-s text-label bg-bg mb-3</value>
      <webElementGuid>40cbcaf3-8ca7-48a7-aff2-6cafeb997cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>b6bc4585-d19b-4de4-9e4f-2d0003c62d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>91182a9f-f440-428d-ab69-faf42a984537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd618a6f-0d97-4c36-b8d9-2a38656a43cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-19&quot;)</value>
      <webElementGuid>a24bf51b-5cda-49f2-aab0-b40654e489d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-19']</value>
      <webElementGuid>2fe0df37-4e4f-49f1-acad-e0bedc6cc3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-combobox-button-18']/input</value>
      <webElementGuid>0a49c081-d782-4217-b593-7bd66df3a90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div[2]/div[5]/div/div/button/input</value>
      <webElementGuid>37363352-9b2a-4c12-a4ca-c9cc0d1c962c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'headlessui-combobox-input-19' and @name = 'role' and @placeholder = 'Role' and @type = 'text']</value>
      <webElementGuid>a67b6134-f9ad-4bd3-81e8-1cc7f22d2f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
