<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse_avatar</name>
   <tag></tag>
   <elementGuidId>5b9d8319-0024-426e-a65b-7ff08d6eafc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='avatar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;avatar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>430879bf-2b80-400c-95ed-37a6bb9cc85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>cb54425d-9d28-4ec4-b6c7-263a52f4f6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>ac60228d-d6b1-44b9-99e7-46d705c5f83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full absolute h-[80%] opacity-0 cursor-pointer top-0</value>
      <webElementGuid>7ab66f64-21fd-4da5-89fa-6a3e35968487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>ac70d959-9319-4e04-8c09-7e6fc44f2218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-12&quot;)/div[@class=&quot;flex min-h-screen items-center justify-center px-4 pt-4 text-center sm:block sm:items-end sm:p-0 lg:pb-20&quot;]/div[@class=&quot;relative inline-block w-[95%] flex-grow transform overflow-hidden text-left align-bottom transition-all sm:my-8 sm:w-[auto] sm:align-middle&quot;]/div[@class=&quot;w-full sm:w-[579px] p-8 bg-white rounded-xl&quot;]/form[1]/section[1]/div[@class=&quot;bg-bg rounded-xl min-h-[190px] flex flex-col justify-center items-center text-label relative border-[1px] border-dashed border-placeholder&quot;]/input[@class=&quot;w-full absolute h-[80%] opacity-0 cursor-pointer top-0&quot;]</value>
      <webElementGuid>9883a188-a7dd-4950-a247-640ff16a17fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='avatar']</value>
      <webElementGuid>a5d96419-4409-4bae-8115-f4dffcc38498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-12']/div/div[2]/div/form/section/div/input[2]</value>
      <webElementGuid>1119be71-2053-404c-81d9-c2b99453aa0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>c5e4fe63-7513-4451-92cc-a397a20b8beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'avatar' and @type = 'file']</value>
      <webElementGuid>b6e27d8c-1652-4445-ab08-1ccde112842a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
