<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_district_cakung</name>
   <tag></tag>
   <elementGuidId>e80cd8f8-6c54-4748-a01b-fd690adb5050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-combobox-option-62']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-option-62 > span.block.truncate.font-normal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>98419781-c392-4c94-9898-a606913a55c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block truncate font-normal</value>
      <webElementGuid>487b8607-a399-4dfc-bb6f-32f3d2ff3a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CAKUNG</value>
      <webElementGuid>b24846fd-06a5-4630-af06-d863781b359a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-option-62&quot;)/span[@class=&quot;block truncate font-normal&quot;]</value>
      <webElementGuid>d6cfc281-b47d-422c-bfdd-5ad42b400e7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='headlessui-combobox-option-62']/span</value>
      <webElementGuid>127e97f5-bc66-4187-a811-167585b4e173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PASAR REBO'])[1]/following::span[1]</value>
      <webElementGuid>96f67dc0-f0ee-425c-969c-3f486d104354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KRAMATJATI'])[1]/following::span[2]</value>
      <webElementGuid>f86a7301-004f-457a-a1e8-60743936ca50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUREN SAWIT'])[1]/preceding::span[1]</value>
      <webElementGuid>5d78794e-fba2-43a9-a605-b34e2334559f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAKASAR'])[1]/preceding::span[2]</value>
      <webElementGuid>435913f7-7116-4b68-af9d-bc7eed2f0e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CAKUNG']/parent::*</value>
      <webElementGuid>4f7bd3a3-acdf-42f0-bd78-8906b7a681b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span</value>
      <webElementGuid>275bb472-dfc1-470f-acc1-9a95d5f7d813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CAKUNG' or . = 'CAKUNG')]</value>
      <webElementGuid>948fe07c-c366-483c-8cc0-3184e1738243</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
