<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_village</name>
   <tag></tag>
   <elementGuidId>602946f5-e29d-4f37-b1ef-198cc1fc38cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-input-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77d19f14-083b-4fcf-b274-1722ededa79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-10</value>
      <webElementGuid>790d1ce9-b2d4-44a6-8903-174983c72a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>village</value>
      <webElementGuid>c359daf8-6cf6-48c6-b947-2a2f783cf7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-left border-2 border-line rounded-xl p-4 text-s text-label bg-bg </value>
      <webElementGuid>57a4cab4-9523-4727-bf47-db106f8c2e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kelurahan</value>
      <webElementGuid>00747d87-03af-4aa8-b649-db4d18da4100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>348eaeca-193f-4691-aa0a-a97cd76e4452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd3a1bea-fbc7-44f1-ba73-89e2d85b6680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c26c7960-6a28-4171-b0f4-54db32adf5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-10&quot;)</value>
      <webElementGuid>c915a0d4-77b6-4062-a996-169eab02c52d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-10']</value>
      <webElementGuid>c000f2d2-6963-46ec-b52b-62d2485e8a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-combobox-button-9']/input</value>
      <webElementGuid>6af751c3-c833-40b6-b6e7-6959de375fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/button/input</value>
      <webElementGuid>09582f78-1734-48b4-bece-10ee5831f1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'headlessui-combobox-input-10' and @name = 'village' and @placeholder = 'Pilih Kelurahan' and @type = 'text']</value>
      <webElementGuid>87ae920a-029f-4057-8e1e-cd09f4979802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
