<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_phone_number</name>
   <tag></tag>
   <elementGuidId>fdf18a63-cb7c-4abc-851d-e553fced0b73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobile_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mobile_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cdf9fb8-386d-4652-956b-1bf40307f74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobile_number</value>
      <webElementGuid>f9e07acc-8890-48ea-97f4-84b21f4d0adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile_number</value>
      <webElementGuid>5d58c055-b67b-4c52-95ad-7f822a6e8bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aacaa02f-0372-4ff5-95a1-3b7ea0534ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type Phone</value>
      <webElementGuid>cf09c057-c808-47b4-9a68-318445e967b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>ab454535-b0d2-4bac-b4d8-84d6b431380f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 h-14 w-full rounded-xl pr-4 focus:outline-[1px]  bg-bg cursor-not-allowed focus:outline-none focus:outline-0  border-line border-2 pl-4</value>
      <webElementGuid>08447d65-3f81-48cd-9867-16dd312d9373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62982929223</value>
      <webElementGuid>0f76cb97-6576-44a3-b103-4217b2839daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile_number&quot;)</value>
      <webElementGuid>c6f4c134-f816-46e5-a160-4d44cf7791ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobile_number']</value>
      <webElementGuid>7fc9ba3d-32bf-4705-9641-22e89d9778d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/main/section/div/form/div/div[2]/div[3]/label/input</value>
      <webElementGuid>508378d7-9396-4752-bd75-d9990b9c0957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>ab058da1-9833-4b74-a649-3960d87625ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'mobile_number' and @id = 'mobile_number' and @type = 'text' and @placeholder = 'Type Phone']</value>
      <webElementGuid>8f8a961b-2ca7-4db0-88cd-79b5534a3c91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
