<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jl. Green Sedayu 7, Cakung Timur, _71ccb5</name>
   <tag></tag>
   <elementGuidId>e52f2814-60be-4e48-a2ef-ff30f29c0491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b5e16267-d2d2-4228-ad24-6af21c3f1216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>ecaf112d-c0b1-49c5-a9b1-00bfba5316ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alamat</value>
      <webElementGuid>04e042e5-80a4-4408-857b-af05fe0ac848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c966f938-21bb-45ec-963b-42d90fc2cc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> rounded-xl mt-1 pr-4 pt-3 h-34 py-20 w-full bg-bg  focus:outline-none  focus:outline-[1px] cursor-not-allowed  undefined pl-4</value>
      <webElementGuid>8e1ff69d-be8c-4d9e-9a88-4f89eb43d504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jl. Green Sedayu 7, Cakung Timur, Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta</value>
      <webElementGuid>0d8d34ce-f452-4732-9b6b-9149490c10ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;flex flex-col w-100 h-[100vh] overflow-hidden&quot;]/main[@class=&quot;bg-bg lg:flex  overflow-y-auto lg:overflow-hidden flex-grow relative&quot;]/section[@class=&quot;relative h-full flex flex-col lg:w-4/5&quot;]/div[@class=&quot;flex-grow overflow-y-auto py-5 sm:px-14&quot;]/form[@class=&quot;rounded-lg bg-white p-7 my-10 shadow-md&quot;]/div[@class=&quot;grid grid-cols-1 sm:grid-cols-2&quot;]/div[@class=&quot;space-y-5&quot;]/div[@class=&quot;mb-3&quot;]/label[@class=&quot;relative text-label focus-within:text-label block&quot;]/textarea[@class=&quot;rounded-xl mt-1 pr-4 pt-3 h-34 py-20 w-full bg-bg  focus:outline-none  focus:outline-[1px] cursor-not-allowed  undefined pl-4&quot;]</value>
      <webElementGuid>bf3591da-f195-4cf4-a1cf-8ee19ebc610a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='address']</value>
      <webElementGuid>affb4669-9ccd-4185-a571-8d9464f69a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/main/section/div/form/div/div[2]/div[8]/label/textarea</value>
      <webElementGuid>75c0369d-696f-4e75-97dc-a7a6c10a5216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::textarea[1]</value>
      <webElementGuid>c197a58d-d3dd-4a81-a5e5-8ac5b72d4b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Pos'])[1]/preceding::textarea[1]</value>
      <webElementGuid>7ff1fa1c-6aac-4b7f-ab24-6145b2309390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profile'])[1]/preceding::textarea[1]</value>
      <webElementGuid>7a55805a-709d-4e78-8d16-8eaa116f09a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jl. Green Sedayu 7, Cakung Timur, Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta']/parent::*</value>
      <webElementGuid>b3360d7c-4ef0-4f92-9d2b-8de0f5740328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>dcea2010-a52f-4b4d-a2e0-c3e4b5ee7d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'address' and @placeholder = 'Alamat' and (text() = 'Jl. Green Sedayu 7, Cakung Timur, Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta' or . = 'Jl. Green Sedayu 7, Cakung Timur, Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta')]</value>
      <webElementGuid>a7e9f12f-067a-4700-807b-3ef4fbe3ea5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
