<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>office_tambah_dropdown_provinsi_jawa_barat</name>
   <tag></tag>
   <elementGuidId>1a07b1a4-6fc3-429e-a5b7-ce286893466f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-option-205</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-combobox-option-205']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b62c00bd-748a-4311-b968-09f9d3aa4bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-default select-none relative py-2 pl-10 pr-4 text-gray-900</value>
      <webElementGuid>568ddffd-e1e1-45f5-b627-d7cce2ccfd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-option-205</value>
      <webElementGuid>1043f98a-7b99-4f61-ac41-ab3ca1e06bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>da050898-8326-40eb-ad69-fba338950d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6ea1e962-93ab-4892-8182-d82590a752c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JAWA BARAT</value>
      <webElementGuid>5dd74698-4cc2-44b3-9ee3-b244834f33c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-option-205&quot;)</value>
      <webElementGuid>5d986521-eae6-4b56-92ec-8393939e2d19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='headlessui-combobox-option-205']</value>
      <webElementGuid>d62a0423-61bc-4899-b789-b2b9f6bb79f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headlessui-combobox-options-193']/li[12]</value>
      <webElementGuid>da48d5f7-a4cd-445c-90b6-b38f7c498139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DKI JAKARTA'])[1]/following::li[1]</value>
      <webElementGuid>8b19454f-4305-470e-99d7-73702ff29fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEPULAUAN RIAU'])[1]/following::li[2]</value>
      <webElementGuid>4fb02f09-d787-4381-939b-27fed2432539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAWA TENGAH'])[1]/preceding::li[1]</value>
      <webElementGuid>f2b06919-94b0-4fd4-8ebb-f03126c54499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]</value>
      <webElementGuid>d349d6d9-5c2f-4405-9875-fd2af0c96d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'headlessui-combobox-option-205' and (text() = 'JAWA BARAT' or . = 'JAWA BARAT')]</value>
      <webElementGuid>be161f8b-46e5-4bc1-b24b-d77e58584078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
