<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>office_tambah_button_pin_point</name>
   <tag></tag>
   <elementGuidId>667f6ed5-8a0e-4dbc-9331-8ba32d25792c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.flex.items-center.bg-white.border.border-line.shadow-low.p-3.rounded-xl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc0674bd-a3cb-4905-bcc8-56e6c037fa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cade86b-abf0-4acd-9b31-3e13e60d0262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center bg-white border border-line shadow-low p-3 rounded-xl</value>
      <webElementGuid>9948357e-5de7-48ae-af3a-569fcb5805eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atur Lokasi</value>
      <webElementGuid>0100f99b-fbc4-466d-b0c6-29d30d9a6f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-4&quot;)/div[@class=&quot;flex min-h-screen items-center justify-center px-4 pt-4 text-center sm:block sm:items-end sm:p-0 lg:pb-20&quot;]/div[@class=&quot;relative inline-block w-[95%] flex-grow transform overflow-hidden text-left align-bottom transition-all sm:my-8 sm:w-[auto] sm:align-middle&quot;]/div[@class=&quot;bg-white border-[1px] border-solid border-line rounded-xl shadow-low px-3 lg:px-6 py-6 w-full sm:w-[502px]&quot;]/form[1]/div[@class=&quot;w-full h-[230px] rounded-xl flex items-center justify-center bg-map bg-cover&quot;]/button[@class=&quot;flex items-center bg-white border border-line shadow-low p-3 rounded-xl&quot;]</value>
      <webElementGuid>e5c1ee21-8443-4fb2-a049-40f34dc75a23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>37dddc13-5c60-4e18-a8bb-d66f522f63c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-4']/div/div[2]/div/form/div[11]/button</value>
      <webElementGuid>2a11df4b-d023-4687-85d7-ebdaca58ea5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Gedung/Bangunan'])[1]/following::button[1]</value>
      <webElementGuid>ec578a5f-d918-4a82-ab28-77144f415672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telepon'])[5]/following::button[3]</value>
      <webElementGuid>5c8d878c-8486-4fc7-a203-82faa1423226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>815bf1f5-e386-411b-9484-4ad4259d7f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button</value>
      <webElementGuid>2e524d77-f7e2-455a-ac65-2eb2c02d7fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Atur Lokasi' or . = 'Atur Lokasi')]</value>
      <webElementGuid>07108152-f6b3-4a28-9ead-283fae689c33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
