<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>office_tambah_pin_point_button_terapkan_lokasi</name>
   <tag></tag>
   <elementGuidId>193ae74b-26a5-4343-bb80-4b6db21eca94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.px-6.py-4.font-semibold.text-white.bg-secondary.rounded-xl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ddea89fa-3e6e-4df6-9476-00c424295f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-6 py-4 font-semibold text-white bg-secondary rounded-xl</value>
      <webElementGuid>b0987961-5fd7-4b08-b781-518b6b139416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terapkan Lokasi</value>
      <webElementGuid>e6069c7a-9db4-4404-9b01-fcaac4b17d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-424&quot;)/div[@class=&quot;flex min-h-screen items-center justify-center px-4 pt-4 text-center sm:block sm:items-end sm:p-0 lg:pb-20&quot;]/div[@class=&quot;relative inline-block w-[95%] flex-grow transform overflow-hidden text-left align-bottom transition-all sm:my-8 sm:w-[auto] sm:align-middle&quot;]/div[@class=&quot;w-full sm:w-[957px] px-6 py-5 bg-white&quot;]/div[@class=&quot;flex flex-col sm:flex-row gap-3 sm:gap-0 justify-end mt-6&quot;]/button[@class=&quot;px-6 py-4 font-semibold text-white bg-secondary rounded-xl&quot;]</value>
      <webElementGuid>81b7dfdb-a98c-45dc-8306-41210ee7edd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-424']/div/div[2]/div/div[3]/button[2]</value>
      <webElementGuid>08224310-a275-417d-a70f-8281a9b76216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>c26775da-8a88-4c14-b6d1-ad18382941f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report a map error'])[1]/following::button[2]</value>
      <webElementGuid>73884ffb-1143-4000-8372-502c31437133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banten'])[1]/preceding::button[2]</value>
      <webElementGuid>f1a93a89-5ab5-4691-aa3b-8f6e16f98d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/preceding::button[2]</value>
      <webElementGuid>0ebb67ce-035f-47f3-8429-558f21f34edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terapkan Lokasi']/parent::*</value>
      <webElementGuid>9f1ab54b-c7e5-4848-99df-a3797962c4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>f26d8ec8-052f-44e7-b7b4-5ac19aeb319f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Terapkan Lokasi' or . = 'Terapkan Lokasi')]</value>
      <webElementGuid>668fdb58-9e47-41cb-8707-aa569c01e034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
