<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>office_tambah_dropdown_provinsi_jawa_timur</name>
   <tag></tag>
   <elementGuidId>f4bf030d-f0f4-4c0a-8da0-a5fc0ee4b8b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-option-208</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-combobox-option-208']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>99908202-e01b-4835-97c9-bf61ce5e0a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-default select-none relative py-2 pl-10 pr-4 text-gray-900</value>
      <webElementGuid>b471db48-3405-42cf-869c-1bf20e33a4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-option-208</value>
      <webElementGuid>6e507a6d-e46b-4a4e-9ec5-087468888d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c613d778-6405-4ccc-8fc6-fbabbeec817f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1fe77211-0f01-451b-ba43-5562f92f2a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JAWA TIMUR</value>
      <webElementGuid>da9d40b9-fd74-45bf-8add-8fa754030ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-option-208&quot;)</value>
      <webElementGuid>d2f9dfc9-182b-4416-8b34-2798de4e6237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='headlessui-combobox-option-208']</value>
      <webElementGuid>60a01438-258e-4d50-abc2-3e5908bae55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headlessui-combobox-options-193']/li[15]</value>
      <webElementGuid>bbec3767-023b-4c0b-8b44-321f361cea2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAERAH ISTIMEWA YOGYAKARTA'])[1]/following::li[1]</value>
      <webElementGuid>90d36640-cd11-4e40-a707-a2227a0950f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAWA TENGAH'])[1]/following::li[2]</value>
      <webElementGuid>f8830489-6fc5-4a5e-b63f-56c0db71596c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANTEN'])[1]/preceding::li[1]</value>
      <webElementGuid>89210cf1-f2bf-4afb-88ed-818722e5ea0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]</value>
      <webElementGuid>3ec5a505-df8c-4cb9-80a9-cb7f739d416e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'headlessui-combobox-option-208' and (text() = 'JAWA TIMUR' or . = 'JAWA TIMUR')]</value>
      <webElementGuid>2f2a5dfa-7f2a-437c-a1cb-aea7add0acad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
