<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>office_tambah_dropdown_kota_jakarta_barat</name>
   <tag></tag>
   <elementGuidId>1b731143-a08c-4b49-b2d8-0d4f0681fcee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-option-279</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2552ad72-ac29-43ec-84a6-122ef267ddb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-default select-none relative py-2 pl-10 pr-4 text-gray-900</value>
      <webElementGuid>212eafc6-280b-4e9e-a964-f6858de4318d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-option-279</value>
      <webElementGuid>1ea9953e-96e2-4e0f-b199-3334183ef114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7a166e96-f762-498c-a0fa-5e84454b9132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b24f4f46-91a7-4d4e-acd1-23102c07f06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOTA ADM. JAKARTA BARAT</value>
      <webElementGuid>1056a53a-9916-460b-aebb-e4cad6ee4b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-option-279&quot;)</value>
      <webElementGuid>00adcc3c-83f1-48e1-a610-8aa75db3ca78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='headlessui-combobox-option-279']</value>
      <webElementGuid>c1289d97-baf7-4646-b723-a3fe13d72a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headlessui-combobox-options-275']/li[4]</value>
      <webElementGuid>20b5d3ba-7e38-45f6-b485-8b84ba09091b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA ADM. JAKARTA UTARA'])[1]/following::li[1]</value>
      <webElementGuid>89a0236b-2158-499e-a425-4ddce4b3b079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA ADM. JAKARTA PUSAT'])[1]/following::li[2]</value>
      <webElementGuid>841a15b4-ec16-4391-a690-9106a7733879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA ADM. JAKARTA SELATAN'])[1]/preceding::li[1]</value>
      <webElementGuid>bc0eeb4b-0d42-44c4-9e61-ea7426b9004f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>00f93263-8de2-4d18-9c94-79550223d040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'headlessui-combobox-option-279' and (text() = 'KOTA ADM. JAKARTA BARAT' or . = 'KOTA ADM. JAKARTA BARAT')]</value>
      <webElementGuid>085b1f59-380d-45dc-8dba-0057ff0cf0f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
