<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>office_tambah_initial_name</name>
   <tag></tag>
   <elementGuidId>21dafd73-2c51-42f0-a868-9014f585d36d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff588edc-77de-4bae-b015-a9324b596b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>925cd541-2216-4c93-acec-943b5f3953b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>bae81e04-1518-480c-9099-93f4105edbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9c9de1a-0f81-47a4-9f34-33a4316e48f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>RPL JKT</value>
      <webElementGuid>898e5d61-0d9c-4aa8-aae9-eaa5d29c9869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 h-14 w-full rounded-xl pr-4 focus:outline-[1px]  focus:outline-secondary bg-white  border-line border-2 pl-4</value>
      <webElementGuid>0808b555-e790-473f-8866-6fba5f022407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;code&quot;)</value>
      <webElementGuid>b289294a-8f11-4d26-8e5c-8a0e838b6e04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='code']</value>
      <webElementGuid>bff9becc-d711-4be1-8031-cb990ee437e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-4']/div/div[2]/div/form/div[3]/label/input</value>
      <webElementGuid>b59ae885-3245-44f5-ad3b-9820ee1e175e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>b32558d1-7206-40c6-8507-0a8961527502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'code' and @id = 'code' and @type = 'text' and @placeholder = 'RPL JKT']</value>
      <webElementGuid>c3db52cb-533f-4115-8784-bd0c35142be8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
