<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>office_button_Edit</name>
   <tag></tag>
   <elementGuidId>be08acad-5338-478d-bcef-8202b9343809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section/main/section/div/table/tbody/tr/td[4]/div/span[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>642707e3-1be0-44e0-b74b-88dddad1734c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex text-secondary</value>
      <webElementGuid>fd8a7e89-3a18-4242-9742-49d4117df16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>d69e99ff-3688-4aa1-afdc-c25cb60919c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;flex flex-col w-100 h-[100vh] overflow-hidden&quot;]/main[@class=&quot;bg-bg lg:flex  overflow-y-auto lg:overflow-hidden flex-grow relative&quot;]/section[@class=&quot;relative h-full flex flex-col lg:w-4/5&quot;]/div[@class=&quot;flex-grow overflow-y-auto py-5 sm:px-14&quot;]/table[@class=&quot;flex flex-col w-full table-auto sm:table&quot;]/tbody[1]/tr[@class=&quot;border-b-2 border-line flex flex-col sm:table-row my-5 sm:my-0&quot;]/td[@class=&quot;break-all bg-white p-4 text-body&quot;]/div[@class=&quot;flex&quot;]/span[@class=&quot;flex-1 text-xs&quot;]/div[@class=&quot;flex flex-col gap-3 sm:whitespace-nowrap&quot;]/button[@class=&quot;flex text-secondary&quot;]</value>
      <webElementGuid>63ec1ae3-0745-44ea-be94-70ab2e6fced1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/main/section/div/table/tbody/tr/td[4]/div/span[2]/div/button</value>
      <webElementGuid>eb8cd7b6-ffae-470b-ad6e-b30a8528851a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telepon'])[1]/following::button[1]</value>
      <webElementGuid>51bb76ce-a14e-4e0c-8f98-b4baf2bc96be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See Map'])[1]/following::button[1]</value>
      <webElementGuid>2cc87067-7c49-461c-8381-74b2fcf38b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office'])[4]/preceding::button[1]</value>
      <webElementGuid>cc072f39-5d35-435f-a3bb-e6e8870c9c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RPL SUNTER'])[1]/preceding::button[1]</value>
      <webElementGuid>f0eb4a32-b84b-423f-ac85-4af8e6d7b644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>8ad710f4-75c9-4584-9d6f-0d6a33f6e101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/button</value>
      <webElementGuid>764261e5-c5b0-4b4d-9106-4eb7add70dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>ce52ea3b-8bfb-48f9-b972-b620822478c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
