<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>office_tambah_dropdown_provinsi</name>
   <tag></tag>
   <elementGuidId>fb63644c-e9fb-4691-8201-04b8b0dc269d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.absolute.inset-y-0.right-0.flex.items-center.pr-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-combobox-button-8']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>30a25ad0-ef3a-4126-92c0-26f7438d23ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-y-0 right-0 flex items-center pr-2</value>
      <webElementGuid>ba374825-5b83-483b-aa4d-be0dd1e6dbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-button-8&quot;)/div[@class=&quot;absolute inset-y-0 right-0 flex items-center pr-2&quot;]</value>
      <webElementGuid>f3ec6092-d6da-4c04-8334-f4f2eb49bdbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-combobox-button-8']/div</value>
      <webElementGuid>1da4a53a-dbdd-4789-b21e-2fc0dfe996c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telepon'])[5]/following::div[4]</value>
      <webElementGuid>ecffe6e4-a563-4cce-b39c-57e5eacd42b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[5]</value>
      <webElementGuid>df76ad40-0ef3-4106-84e8-896852e51dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Gedung/Bangunan'])[1]/preceding::div[5]</value>
      <webElementGuid>2ab67ff0-1e4f-4a92-baba-ad65cd7c5750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atur Lokasi'])[1]/preceding::div[6]</value>
      <webElementGuid>3124e8b9-d652-4042-8e1d-2ff5b15afaf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>6fa65f97-01a3-4043-887b-1bd91a537722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
