<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Akun Staff</name>
   <tag></tag>
   <elementGuidId>68038f72-4cb7-4de4-bfaf-d553e43f3856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section/main/aside/div/nav/section[5]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6213347-c322-451e-be74-2b9dc245e2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full has-tooltip text-left py-3 px-5 rounded-xl text-xs font-semibold text-label mb-3 flex items-center stroke-label cursor-pointer justify-start</value>
      <webElementGuid>b9f78e8a-1b8a-438e-ad25-ca2f33cc30b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dashboard/accounts</value>
      <webElementGuid>02107575-1981-4ebb-8d90-28725556af31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akun Staff</value>
      <webElementGuid>09f25abe-3f86-4367-8e1f-62f21d1e9c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;flex flex-col w-100 h-[100vh] overflow-hidden&quot;]/main[@class=&quot;bg-bg lg:flex  overflow-y-auto lg:overflow-hidden flex-grow relative&quot;]/aside[@class=&quot;transition-all duration-200 bg-white h-full absolute lg:relative top-0 left-[-100%] lg:left-0 z-10 lg:pt-0 w-4/5 lg:w-1/5&quot;]/div[@class=&quot;h-full overflow-y-auto w-full relative&quot;]/nav[@class=&quot;py-5 px-3 w-full&quot;]/section[5]/a[@class=&quot;w-full has-tooltip text-left py-3 px-5 rounded-xl text-xs font-semibold text-label mb-3 flex items-center stroke-label cursor-pointer justify-start&quot;]</value>
      <webElementGuid>a6b76133-ac6c-46e4-8082-700a32ba7ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/main/aside/div/nav/section[5]/a[2]</value>
      <webElementGuid>5ea6d772-0650-4914-afbb-ff4be03bad13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Akun Staff')]</value>
      <webElementGuid>6b14131c-c106-4979-9537-2ad721356d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[1]/following::a[1]</value>
      <webElementGuid>8474c33f-2f98-445d-ac67-08fdb5884301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/following::a[2]</value>
      <webElementGuid>c3fb993e-639a-4f98-9bdd-8a7fb9426010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Customer'])[1]/preceding::a[1]</value>
      <webElementGuid>5062d3f0-fbec-4406-857d-16727c3bc7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Profile'])[1]/preceding::a[2]</value>
      <webElementGuid>a03d491b-053a-4888-9452-78078379e06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akun Staff']/parent::*</value>
      <webElementGuid>e6a3e621-c40c-41f5-8b49-ec3dc8444ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dashboard/accounts')]</value>
      <webElementGuid>5e70cc9c-085e-4a26-97cb-74a55a0ab85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/a[2]</value>
      <webElementGuid>e34041e2-5ed7-4f90-8741-5ad42f46a4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dashboard/accounts' and (text() = 'Akun Staff' or . = 'Akun Staff')]</value>
      <webElementGuid>c86bbe80-aab0-49ed-b349-6f803d603793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
