<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_telepon</name>
   <tag></tag>
   <elementGuidId>0c07f045-efff-4891-88ba-889e60008e56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telepon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telepon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f21df87-200a-4ebf-8161-a7da8428bad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telepon</value>
      <webElementGuid>cf1aed68-9a69-43d1-9cb2-857e0390de44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telepon</value>
      <webElementGuid>6f8822be-8703-4760-bf72-a6a96f389beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6dd6c615-3c54-4c4b-84c5-611712af848e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Telepon</value>
      <webElementGuid>111ebbb7-f61d-4bf8-b099-f18cf1b00f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>7295f54c-98f4-4033-bc8d-5fd6f0203c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 h-14 w-full rounded-xl pr-4 focus:outline-[1px]  focus:outline-secondary bg-white  border-line border-2 pl-4</value>
      <webElementGuid>a6a25f4d-e930-44a5-afa9-5f9fd96a7df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telepon&quot;)</value>
      <webElementGuid>938c28f8-3ae1-4049-b53c-e740a9c6acfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telepon']</value>
      <webElementGuid>e94f35c2-7846-4ff1-a00c-2bc23bf83092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-12']/div/div[2]/div/form/div/div[2]/div[6]/label/input</value>
      <webElementGuid>1eb53cc1-8365-4f13-8230-8ac6a89fea09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/label/input</value>
      <webElementGuid>b6989ab3-3667-40d0-8be6-9580694abb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'telepon' and @id = 'telepon' and @type = 'text' and @placeholder = 'Telepon']</value>
      <webElementGuid>e3296df5-2b4b-48ec-a8b3-4a8271fba9ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
