<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Password_confirm</name>
   <tag></tag>
   <elementGuidId>9d3a96b8-dd77-4796-9f61-cd199efde65b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60a626fb-8348-4980-93ce-88f46d1da3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm</value>
      <webElementGuid>ea85663f-e293-4b2b-9e3e-d4b81f9ae69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cdedce15-127b-4bd7-a36e-57bc6a834a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm</value>
      <webElementGuid>8df72846-2ccd-40be-8182-a8ff18de89c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Konfirmasi Password</value>
      <webElementGuid>1b7f3d67-e0af-40a7-b5fc-2a2016e15744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white border-2 border-line rounded-xl  pr-4 h-14  focus:outline-none w-full undefined pl-4</value>
      <webElementGuid>56f92c1a-c92c-4ca6-9a66-00046dfda6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm&quot;)</value>
      <webElementGuid>968cb84d-9f8f-4013-bb0f-9cde292ca9af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm']</value>
      <webElementGuid>390f0b6d-a51b-4036-b788-3cb9ebfe2671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-12']/div/div[2]/div/form/div/div[2]/div[5]/label/input</value>
      <webElementGuid>171b4db1-61a5-41b9-bbe4-d72d68c34244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/input</value>
      <webElementGuid>08675ca7-c5bc-41fc-9b74-3fc27d72adca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'confirm' and @type = 'password' and @id = 'confirm' and @placeholder = 'Konfirmasi Password']</value>
      <webElementGuid>984517c2-c162-4901-8a21-d167740a7ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
