<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dashboard_accessbility</name>
   <tag></tag>
   <elementGuidId>d6b20402-da86-4ef3-a942-252cd9af5876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mQuotation-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mQuotation-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>120fcc31-43da-4fa5-8acc-081a92a0b1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>de275f61-669a-4cb0-8e6f-53021c1112d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mQuotation-1</value>
      <webElementGuid>f682851b-3aa6-4515-ad8b-816dfb2f9b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox w-6 h-6 rounded-md mr-4 form-check appearance-none checked:border-0 checked:bg-secondary border-2 border-placeholder</value>
      <webElementGuid>a33621ad-7e9c-4c26-ab01-8938c13444aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accessbility</value>
      <webElementGuid>9ea0f0e9-7750-4400-93c3-2046c05d0920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>279a5faa-c0b6-4f7a-a6ec-af907a5e1418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mQuotation-1&quot;)</value>
      <webElementGuid>a76429cd-81da-4b29-b63e-3ffe6a465fce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mQuotation-1']</value>
      <webElementGuid>5a7a12aa-bf53-4984-ac94-ef589484df1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-12']/div/div[2]/div/form/div/div[2]/div[9]/div[2]/input</value>
      <webElementGuid>41af65fd-106b-40c7-9e03-35fc221c9f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>bae4d9b8-5e2b-4ab0-8d2d-17b038121d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mQuotation-1' and @name = 'accessbility']</value>
      <webElementGuid>ac7dd1fa-4578-429b-85b6-6cfb74f77e04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
