<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_role</name>
   <tag></tag>
   <elementGuidId>d373e769-d26a-4bd0-956d-8ef0d6648bc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-input-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2a2a39d-d94f-44d6-a52d-046402a52027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-19</value>
      <webElementGuid>ae0be317-9322-4338-93f9-520923bb79f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>e644d8c3-b95f-4c82-9c85-16161359fbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-left border-2 border-line rounded-xl p-4 text-s text-label  bg-white rounded-xl  focus:outline-0   mb-3</value>
      <webElementGuid>4f1e8227-5384-46c2-8f52-b5e23d47e933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>1f8308bb-e61a-44ee-ae89-74ba08d06f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>a573e327-7612-4b7b-b4c9-0814a3e2acdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1351f9e-c070-4cdd-b009-9f7902186db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>181a97cc-fe05-4938-a30f-ef549748c7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-19&quot;)</value>
      <webElementGuid>a8f2a38f-1db9-40fb-b81c-f039ce7f5d03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-19']</value>
      <webElementGuid>5f68aaa2-f3a4-46e3-b06f-ce40044d5835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-combobox-button-18']/input</value>
      <webElementGuid>0da1a781-ce1d-443c-8a3b-11596418e545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div[2]/div[7]/div/div/button/input</value>
      <webElementGuid>dde0161b-5b78-4dfc-ac3b-dc90e3982f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'headlessui-combobox-input-19' and @name = 'role' and @placeholder = 'Role' and @type = 'text']</value>
      <webElementGuid>d2951bab-ac4d-4ef4-8cba-3ffab6ca5ccd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
