<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload Photo_m_office_id</name>
   <tag></tag>
   <elementGuidId>6c261131-0ebe-4104-a180-bae1e1b83883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-input-17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-17']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41a0dd83-f177-4d67-ba4b-9c258ebd71cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-17</value>
      <webElementGuid>297c706d-16ed-4411-9ff7-3966fb22e616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>m_office_id</value>
      <webElementGuid>5ffadeab-fc11-4a99-80d9-890efab26221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-left border-2 border-line rounded-xl p-4 text-s text-label  bg-white rounded-xl  focus:outline-0   </value>
      <webElementGuid>d949d8a2-81e6-4806-a589-e3aa1112c67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>RPL - JKT, RPL - SBY</value>
      <webElementGuid>73af32a1-3141-4ff2-aa0f-c6bc910dd134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>da27e07b-20f9-48b4-9d92-12a76d55e967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0923ba66-8d17-4971-93c2-bc823fe3f9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d74d6d5d-5a5a-4c2d-9e61-a14d6de1aaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-17&quot;)</value>
      <webElementGuid>53e5cddb-1001-4bfa-824f-30a6b34055ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-17']</value>
      <webElementGuid>0e9a54de-be4b-44f0-a645-a3d9076d497c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-combobox-button-16']/input</value>
      <webElementGuid>f91c42d4-545f-4d70-ac95-120458d3047b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div[2]/div/div/div/button/input</value>
      <webElementGuid>0e4b5b34-ce19-40f5-94c8-780754ea7dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'headlessui-combobox-input-17' and @name = 'm_office_id' and @placeholder = 'RPL - JKT, RPL - SBY' and @type = 'text']</value>
      <webElementGuid>dffc8d1d-68c8-44b2-86a2-622c0dc6794d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
