<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Sales (1)</name>
   <tag></tag>
   <elementGuidId>7e35de70-d793-41f0-bd84-888e0a115593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-option-39</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-combobox-option-39']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a63ee17c-ff26-49e9-b03b-49ddaeff61b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-default select-none relative py-2 pl-10 pr-4 text-secondary bg-teal-600</value>
      <webElementGuid>9ea9a43a-9ac6-4fbc-97c0-22179cb12d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-option-39</value>
      <webElementGuid>91c64d55-9b60-45dc-b2a5-2ca6924caea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1afdd7f3-cb04-4503-bf1b-4849653aaccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>10d22cb1-656d-4079-b615-eb60fc879d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales</value>
      <webElementGuid>b2dba9c6-8182-4cd1-9837-123e92a5f2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-option-39&quot;)</value>
      <webElementGuid>2e1ed9fc-f390-4752-8975-e6080cb6747d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='headlessui-combobox-option-39']</value>
      <webElementGuid>4a997629-59fd-4e81-88e8-791e869ccc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headlessui-combobox-options-38']/li</value>
      <webElementGuid>40e47fae-e33d-4fd3-9842-3efb2137de2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telepon'])[1]/following::li[1]</value>
      <webElementGuid>aecd4862-f9e5-4545-8dd5-b0cf91121b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Password'])[1]/following::li[1]</value>
      <webElementGuid>3a81ab29-d676-431c-aa0a-1acd3b0a414f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Superadmin'])[1]/preceding::li[1]</value>
      <webElementGuid>82d7f62a-b505-489f-984b-697e1d65bf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>d7b000f6-847c-4c80-98c6-6c08c171babe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'headlessui-combobox-option-39' and (text() = 'Sales' or . = 'Sales')]</value>
      <webElementGuid>9d5a42e8-ffe5-4166-8018-b7dcce72b184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
