<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_division (1)</name>
   <tag></tag>
   <elementGuidId>1bde6892-99f9-4c19-ae06-a8a66b5509b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-input-21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd34f347-adac-4888-9449-13546aba973f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-21</value>
      <webElementGuid>6ba2e82c-4c5d-4361-bcb2-4fd9d8a92150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>division</value>
      <webElementGuid>07843ae2-c01f-420d-bb87-9a94781c2acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-left border-2 border-line rounded-xl p-4 text-s text-label  bg-white rounded-xl  focus:outline-0   mb-3</value>
      <webElementGuid>ce067b6c-c6c4-4c2b-9f3d-7ee1057995a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Divisi</value>
      <webElementGuid>d501b0d4-0378-4826-8783-92c6d1c2a967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>6969c74c-c871-41e5-a58a-42ce1c2c404b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5acedb67-2216-41c7-895f-cb94c5d5aff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>609c374e-59b6-4c11-aeee-44c6135d9482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-21&quot;)</value>
      <webElementGuid>4edbf4ff-76ec-49e7-a46e-abe930a63816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-21']</value>
      <webElementGuid>a05b1f85-e895-4840-ab29-a8a61c3b1fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-combobox-button-20']/input</value>
      <webElementGuid>085b4a74-fb88-4227-a5e0-3410626ec640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/button/input</value>
      <webElementGuid>96d5a074-9b94-455b-98dd-c102a0af5421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'headlessui-combobox-input-21' and @name = 'division' and @placeholder = 'Divisi' and @type = 'text']</value>
      <webElementGuid>effda7fe-f0fb-4a08-afbe-28e11d23e18b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
