<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>role</name>
   <tag></tag>
   <elementGuidId>8bbf87e3-2a8e-4957-9098-f9d80f5a289a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-input-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40f2b5d5-8a23-4d7f-9590-49c6f9e06ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-19</value>
      <webElementGuid>8e2447e0-420a-4c37-9e73-04ec34944b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>4638494a-f772-41ea-b299-4818fce6d352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-left border-2 border-line rounded-xl p-4 text-s text-label  bg-white rounded-xl  focus:outline-0   mb-3</value>
      <webElementGuid>65530032-5bb3-4e67-a9c8-debd6fcf512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>42bbb0ff-e472-4302-830a-00dbd655f90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>b4e3dcc8-2c38-4fc9-805a-a6f3fbeb09fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce3e73a3-3578-4900-80b7-190166881767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9cfc11aa-e19f-430b-a3c9-a8ab43ca33bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-19&quot;)</value>
      <webElementGuid>6c4c414f-61f9-4051-b806-90ce11e91138</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-19']</value>
      <webElementGuid>cad12f31-c054-45cd-abc4-824b28f62c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-combobox-button-18']/input</value>
      <webElementGuid>a5f93f1e-6e7b-4bf5-9aa3-6112ee74310a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div[2]/div[7]/div/div/button/input</value>
      <webElementGuid>e0b9f280-2b6f-474e-a328-8b25da018ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'headlessui-combobox-input-19' and @name = 'role' and @placeholder = 'Role' and @type = 'text']</value>
      <webElementGuid>cc9b6a32-ea1e-473a-9770-a525fe6d91e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
