<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>role_driver</name>
   <tag></tag>
   <elementGuidId>f9c0e663-d087-4d75-a0b3-244eff3fa080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-option-51 > span.block.truncate.font-normal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-combobox-option-51']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>563b3adf-8396-482e-9e95-5478490863d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block truncate font-normal</value>
      <webElementGuid>f8a932b1-2422-4b4c-b201-3842e8140024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Driver</value>
      <webElementGuid>fa2c5a1c-3deb-422b-b148-14edc6395a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-option-51&quot;)/span[@class=&quot;block truncate font-normal&quot;]</value>
      <webElementGuid>c768e3b0-1b5b-4a10-9370-3d37e3d15258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='headlessui-combobox-option-51']/span</value>
      <webElementGuid>e9183b7a-9cc1-4899-a479-4fd4a066536a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finance'])[2]/following::span[1]</value>
      <webElementGuid>e7112ff3-5f42-4230-b680-7fe0f5468a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operasional'])[6]/following::span[2]</value>
      <webElementGuid>c1025393-c3da-4f7f-a1d4-775e7f937fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[4]/preceding::span[1]</value>
      <webElementGuid>8c9c3503-ae15-40d5-9c5b-865cec586b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supervisor'])[1]/preceding::span[2]</value>
      <webElementGuid>b7e8b8e9-3e65-4f4b-b2d1-bc008ee84468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/span</value>
      <webElementGuid>1140e21e-c26b-452d-8640-c6d86ca18322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Driver' or . = 'Driver')]</value>
      <webElementGuid>28351619-05da-46b9-9546-1d2d225d339f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
