<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_master_data</name>
   <tag></tag>
   <elementGuidId>2a587a9a-902d-4bc8-bd5e-c1f7724849a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section:nth-of-type(5) > a.w-full.has-tooltip.text-left.py-3.px-5.rounded-xl.text-xs.font-semibold.text-label.mb-3.flex.items-center.stroke-label.cursor-pointer.justify-start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section/main/aside/div/nav/section[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5de5ae14-0de0-437b-9070-2ae63942ab72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full has-tooltip text-left py-3 px-5 rounded-xl text-xs font-semibold text-label mb-3 flex items-center stroke-label cursor-pointer justify-start</value>
      <webElementGuid>f97090ae-a178-4d75-944f-52dcf6fc44bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dashboard/master-data</value>
      <webElementGuid>1c3e7ff8-9a56-4ebd-9bfb-e3671714f705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Data</value>
      <webElementGuid>d77862aa-db5b-46bb-8d6b-089f0dbfca91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;flex flex-col w-100 h-[100vh] overflow-hidden&quot;]/main[@class=&quot;bg-bg lg:flex  overflow-y-auto lg:overflow-hidden flex-grow relative&quot;]/aside[@class=&quot;transition-all duration-200 bg-white h-full absolute lg:relative top-0 left-[-100%] lg:left-0 z-10 lg:pt-0 w-4/5 lg:w-1/5&quot;]/div[@class=&quot;h-full overflow-y-auto w-full relative&quot;]/nav[@class=&quot;py-5 px-3 w-full&quot;]/section[5]/a[@class=&quot;w-full has-tooltip text-left py-3 px-5 rounded-xl text-xs font-semibold text-label mb-3 flex items-center stroke-label cursor-pointer justify-start&quot;]</value>
      <webElementGuid>30621f78-9b75-4ba7-8184-fc08ae6d2796</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/main/aside/div/nav/section[5]/a</value>
      <webElementGuid>74bf3165-8fad-49f3-9b68-9e21caf7e734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Master Data')]</value>
      <webElementGuid>f368d508-2e92-43b4-ac4d-ed94f36c3033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/following::a[1]</value>
      <webElementGuid>398b7982-e274-4f04-9273-2e475d9a61dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/following::a[1]</value>
      <webElementGuid>e5d43c4f-130a-4d1a-a63f-b058ec44c7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun Staff'])[1]/preceding::a[1]</value>
      <webElementGuid>b929f56d-a0a5-4a65-8cd9-c4925ba3fb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Customer'])[1]/preceding::a[2]</value>
      <webElementGuid>c33ceb39-b942-4313-a983-74e4c66fb151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master Data']/parent::*</value>
      <webElementGuid>eabf8dab-606e-4d98-b26a-abf133081bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dashboard/master-data')]</value>
      <webElementGuid>a03772f3-17ba-44f5-b71a-5f1a14079bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/a</value>
      <webElementGuid>299f9f08-0300-48f1-a9d5-f941a530a4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dashboard/master-data' and (text() = 'Master Data' or . = 'Master Data')]</value>
      <webElementGuid>92f92b2c-910e-4cbf-88ab-e0eba795fea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
