<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Active</name>
   <tag></tag>
   <elementGuidId>4a22817d-c410-413d-95e7-a2a83af6715f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section/main/section/div/div[2]/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.whitespace-nowrap.rounded-xl.py-2.px-3.font-semibold.capitalize.border-2.border-secondary.bg-bg.text-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5fc09aa2-5540-4b71-9e46-f228e8ef888f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>whitespace-nowrap rounded-xl py-2 px-3 font-semibold capitalize border-2 border-secondary bg-bg text-secondary</value>
      <webElementGuid>201c3d62-0a3d-457f-9c0b-8c0dbbc40b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>05483254-6311-41a9-945d-006e8943f025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;flex flex-col w-100 h-[100vh] overflow-hidden&quot;]/main[@class=&quot;bg-bg lg:flex  overflow-y-auto lg:overflow-hidden flex-grow relative&quot;]/section[@class=&quot;relative h-full flex flex-col lg:w-4/5&quot;]/div[@class=&quot;flex-grow overflow-y-auto py-5 sm:px-14&quot;]/div[@class=&quot;p-0 sm:p-7 mb-10&quot;]/div[@class=&quot;my-7&quot;]/div[@class=&quot;flex max-w-full gap-3 py-3 overflow-x-auto sm:overflow-x-hidden sm:py-0&quot;]/button[@class=&quot;whitespace-nowrap rounded-xl py-2 px-3 font-semibold capitalize border-2 border-secondary bg-bg text-secondary&quot;]</value>
      <webElementGuid>67a959da-d0eb-4620-be5e-c7cadb7b0938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/main/section/div/div[2]/div[2]/div/button</value>
      <webElementGuid>5c33c65d-cff3-4af8-9d0c-1109bd06342f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/following::button[1]</value>
      <webElementGuid>022b67fc-e2f3-4d32-a8ce-04c1503783f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Password'])[1]/following::button[2]</value>
      <webElementGuid>a1bb0eca-b667-405a-b9a7-d71cbcaf1340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::button[1]</value>
      <webElementGuid>e15b4975-afd7-4b29-90ea-7ba8a4e15436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Active']/parent::*</value>
      <webElementGuid>f63bb08f-d406-43ad-b0ac-5485ab810611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>729dc366-c1e5-45af-82eb-e59af79cb1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>879fb066-a5fe-45fa-929a-79175506147c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
