<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Inactive</name>
   <tag></tag>
   <elementGuidId>135a7f89-287f-4eac-945c-8da0cdd269e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section/main/section/div/div[2]/div[2]/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.whitespace-nowrap.rounded-xl.py-2.px-3.font-semibold.capitalize.text-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e12102db-3502-4eb8-b1f1-d35a66b1f40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>whitespace-nowrap rounded-xl py-2 px-3 font-semibold capitalize text-label</value>
      <webElementGuid>fe90815f-c411-44c3-8e1a-ff0fb75037e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>b55165f0-450d-4598-a477-f5bb96a863b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;flex flex-col w-100 h-[100vh] overflow-hidden&quot;]/main[@class=&quot;bg-bg lg:flex  overflow-y-auto lg:overflow-hidden flex-grow relative&quot;]/section[@class=&quot;relative h-full flex flex-col lg:w-4/5&quot;]/div[@class=&quot;flex-grow overflow-y-auto py-5 sm:px-14&quot;]/div[@class=&quot;p-0 sm:p-7 mb-10&quot;]/div[@class=&quot;my-7&quot;]/div[@class=&quot;flex max-w-full gap-3 py-3 overflow-x-auto sm:overflow-x-hidden sm:py-0&quot;]/button[@class=&quot;whitespace-nowrap rounded-xl py-2 px-3 font-semibold capitalize text-label&quot;]</value>
      <webElementGuid>82956651-e9db-4663-80d1-b2244ce5bc29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/main/section/div/div[2]/div[2]/div/button[2]</value>
      <webElementGuid>059e3cbb-705b-4dc4-a39c-145e6316013d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::button[1]</value>
      <webElementGuid>df0c72b8-2134-4b10-91a2-5a6a6b6a3294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/following::button[2]</value>
      <webElementGuid>42cb2c0d-4763-4200-9744-476b91a96dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inactive']/parent::*</value>
      <webElementGuid>e5b73134-fd7b-47b8-8923-55c1a80d6351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>7ad46860-2e73-44e2-a00e-d20213d1b8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Inactive' or . = 'Inactive')]</value>
      <webElementGuid>eb3779f1-33e8-432c-ba2e-07bdab79e9a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
