<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detail_user</name>
   <tag></tag>
   <elementGuidId>62545016-0965-467b-b2cb-99aa815a0cfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr[1]/td[6]/div[1]/span[2]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.whitespace-nowrap > a.text-secondary.flex.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7adfc35b-8ad7-4e88-aa20-f5a9b0645d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-secondary flex cursor-pointer</value>
      <webElementGuid>18bc800f-6e79-4b80-953e-094e724682af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>124e062c-139a-4af3-a2f9-03602065dc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;flex flex-col w-100 h-[100vh] overflow-hidden&quot;]/main[@class=&quot;bg-bg lg:flex  overflow-y-auto lg:overflow-hidden flex-grow relative&quot;]/section[@class=&quot;relative h-full flex flex-col lg:w-4/5&quot;]/div[@class=&quot;flex-grow overflow-y-auto py-5 sm:px-14&quot;]/div[@class=&quot;p-0 sm:p-7 mb-10&quot;]/table[@class=&quot;flex flex-col w-full table-auto sm:table&quot;]/tbody[1]/tr[@class=&quot;border-b-2 border-line flex flex-col sm:table-row my-5 sm:my-0&quot;]/td[@class=&quot;break-all bg-white p-4 text-body&quot;]/div[@class=&quot;flex&quot;]/span[@class=&quot;flex-1 text-xs&quot;]/div[@class=&quot;flex whitespace-nowrap&quot;]/a[@class=&quot;text-secondary flex cursor-pointer&quot;]</value>
      <webElementGuid>5d701512-6bd1-49a4-9064-3b933d7288a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/main/section/div/div[2]/table/tbody/tr/td[6]/div/span[2]/div/a</value>
      <webElementGuid>9c1ab059-302a-4e4c-b0e5-dfe54270e966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Detail')]</value>
      <webElementGuid>f24369a7-a130-480e-9c87-5521529cfae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::a[1]</value>
      <webElementGuid>f7020d76-3b37-4856-8f1d-4eb001a500ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>68257c5e-cef2-46f4-a713-d2d3b7202f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User ID'])[2]/preceding::a[1]</value>
      <webElementGuid>f84ed2ca-cfd8-4af6-a52c-f0d0f8d274c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[3]/preceding::a[1]</value>
      <webElementGuid>12fc1570-654c-4b7e-9ce5-522aa16d592a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>abf3cc32-24fb-4d0b-8e54-d34cf41658cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a</value>
      <webElementGuid>841d3eb2-5918-44a5-9c2e-d1086ddc56b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>00aa0c46-bdd9-476f-8889-df502d93d3db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
